
package ventanas;

import java.sql.*;
import clases.Conexion;
import javax.swing.WindowConstants;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author equipo2
 */
public class Interfaz extends javax.swing.JFrame {
String user ,nombre_usuario;
public static int sesion_usuario;
    /**
     * Creates new form Administrador
     */
    public Interfaz() {
        
        initComponents();
        user = Login.user;
        sesion_usuario = 1;
        setSize(400, 430);
        setResizable(false);
        setTitle("Inicio Bienvenido sesion de " + user);
        setLocationRelativeTo(null);
        
       
        
         ImageIcon wallpapper = new ImageIcon("src/images/farm.jpg");
        Icon Icono = new ImageIcon(wallpapper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(),
                jLabel_Wallpaper.getHeight(),Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(Icono);
        this.repaint();
        
        try{
            Connection cnx = Conexion.conectar();
            PreparedStatement pst = cnx.prepareStatement(
            "select nombre_usuario from  usuarios where username = '" + user + "'");
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                nombre_usuario = rs.getString("nombre_usuario");//recuperar el nombre de usuario de la base de datos
            jLabel_NombreUsuario.setText(nombre_usuario);// capturar el nombre  en la interfaz 
            }
        } catch (Exception e){JOptionPane.showMessageDialog(null, "hay algun error en la conexion con la inferfaz");
    }
    }
    @Override
   public Image getIconImage(){
       Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/farmacia.png"));
       return retValue;
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_NombreUsuario = new javax.swing.JLabel();
        jButton_AgregarProducto = new javax.swing.JButton();
        jButton_Verusuarios = new javax.swing.JButton();
        jButton_EliminarProducto = new javax.swing.JButton();
        jButton_ActulizarProducto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel_Wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_NombreUsuario.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        jLabel_NombreUsuario.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_NombreUsuario.setText("jLabel1");
        getContentPane().add(jLabel_NombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 350, 20));

        jButton_AgregarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/addUser.png"))); // NOI18N
        jButton_AgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AgregarProductoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_AgregarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 120, 100));

        jButton_Verusuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/creatividad.png"))); // NOI18N
        jButton_Verusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_VerusuariosActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Verusuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 120, 100));

        jButton_EliminarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/apoyo-tecnico.png"))); // NOI18N
        jButton_EliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EliminarProductoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_EliminarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 120, 100));

        jButton_ActulizarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/editar.png"))); // NOI18N
        jButton_ActulizarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ActulizarProductoActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_ActulizarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 120, 100));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Registrar Producto");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Gestionar Producto");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Eliminar producto ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 110, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Actualizar Producto");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, -1));

        jButton1.setText("Salir ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, -1));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_AgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AgregarProductoActionPerformed
    Registrar_Producto registrarp = new Registrar_Producto();
    registrarp.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton_AgregarProductoActionPerformed

    private void jButton_VerusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VerusuariosActionPerformed
        Ver_Producto verp = new Ver_Producto();
    verp.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton_VerusuariosActionPerformed

    private void jButton_EliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EliminarProductoActionPerformed
       Eliminar_Producto Eliminarp = new Eliminar_Producto();
    Eliminarp.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton_EliminarProductoActionPerformed

    private void jButton_ActulizarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ActulizarProductoActionPerformed
       Actualizar_Producto Actualizarp = new Actualizar_Producto();
   Actualizarp.setVisible(true);
   this.dispose();
    }//GEN-LAST:event_jButton_ActulizarProductoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_ActulizarProducto;
    private javax.swing.JButton jButton_AgregarProducto;
    private javax.swing.JButton jButton_EliminarProducto;
    private javax.swing.JButton jButton_Verusuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_NombreUsuario;
    private javax.swing.JLabel jLabel_Wallpaper;
    // End of variables declaration//GEN-END:variables
}
